### PR TITLE
Fix redis cache documentation

### PR DESCRIPTION
**Pull request by ludaavics**

### CODE REVIEW

**Comment by obendidi** [comment]
Hey @ludaavics ,

Thanks for the PR, 
The reason why `RedisCache` is not part of the `__init__.py` is that `redis` is only an optional dependency, and always importing will break the lib if the user doesn't install the lib with the redis option: `httpx_cache[redis]`

**Comment by ludaavics** [comment]
Ah fair enough... what do you think of `try/except`-ing an `import redis`?

**Comment by obendidi** [comment]
Seems like an anti-pattern with no added value except a slightly better syntax

I prefer to keep the code simple, and have the users import redisCache specifically if needed

**Comment by ludaavics** [comment]
Fair enough... fwiw I tend to go the other way and error on the side of having  slightly more complex library code in order to have simpler user code ... I just like unloading stuff like the exact import path or the optional dependencies from my brain, when i switch from building the library to using the library.

For instance, i usually wait until the last moment to check for optional dependencies... argument is, it doesn't really put any extra burden on the library user, since, if he tries to use a feature that requires an optional dep, things will fail sooner or later... and in exchange, he gets to write his code as if everything he needed was installed

```python
import wrapt

def requires(*dependencies):
    """
    Verifies that dependencies needed for optional features are installed.
    """

    @wrapt.decorator
    def wrapper(decorated, instance, args, kwargs):
        for dependency in dependencies:
            try:
                import_module(dependency)
            except ModuleNotFoundError:
                msg = (
                    f"Optional dependency '{dependency}' "
                    f"is required for function '{decorated.__name__}'. "
                )
                raise ImportError(msg)
        return decorated(*args, **kwargs)

    return wrapper
    
    
@requires("redis")
def do_some_stuff_that_requires_redis():
    pass
 ```
 
Anyway, enough splitting hairs for today... Only the typo in the documentation left, then... thanks!

**Comment by ludaavics** [comment]
@obendidi FYI it looks like this is somehow not reflected in the github docs?

**Comment by obendidi** [comment]
> @obendidi FYI it looks like this is somehow not reflected in the github docs?

Indeed, my bad

I still didn't automate the docs deployment process :sweat_smile: 

Updated :+1:

**Pull request merged**
